// SPEC-REPORT-001: Markdown report generator
import { ReportSummaryByCurrency } from "@/hooks/useReportData";
import { ChartCaptureResult } from "@/lib/chartCapture";

interface MarkdownReportConfig {
  projectName: string;
  periodLabel: string;
  summaryData: ReportSummaryByCurrency[];
  chartCaptures: ChartCaptureResult[];
  generatedAt: Date;
}

function formatAmount(amount: number, currency: string): string {
  return `${currency} ${amount.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function buildSummaryTable(group: ReportSummaryByCurrency): string {
  const header = `| Code | Category | Income (${group.currency}) | Expense (${group.currency}) | Net (${group.currency}) | % |`;
  const sep = `| --- | --- | ---: | ---: | ---: | ---: |`;

  const rows = group.rows.map((row) => {
    const emoji = row.categoryEmoji ? `${row.categoryEmoji} ` : "";
    return `| ${row.categoryCode || "-"} | ${emoji}${row.categoryName} | ${row.income.toLocaleString("en-US", { minimumFractionDigits: 2 })} | ${row.expense.toLocaleString("en-US", { minimumFractionDigits: 2 })} | ${row.net.toLocaleString("en-US", { minimumFractionDigits: 2 })} | ${row.percentage.toFixed(1)}% |`;
  });

  const totalsRow = `| | **Total** | **${group.totalIncome.toLocaleString("en-US", { minimumFractionDigits: 2 })}** | **${group.totalExpense.toLocaleString("en-US", { minimumFractionDigits: 2 })}** | **${group.totalNet.toLocaleString("en-US", { minimumFractionDigits: 2 })}** | |`;

  return [header, sep, ...rows, totalsRow].join("\n");
}

export function generateMarkdownReport(config: MarkdownReportConfig): string {
  const { projectName, periodLabel, summaryData, chartCaptures, generatedAt } =
    config;

  const lines: string[] = [];

  // Title
  lines.push(`# Financial Report: ${projectName}`);
  lines.push(`**Period:** ${periodLabel}`);
  lines.push(`**Generated:** ${generatedAt.toLocaleString()}`);
  lines.push("");

  // Summary tables by currency
  lines.push("## Summary");
  lines.push("");
  for (const group of summaryData) {
    if (summaryData.length > 1) {
      lines.push(`### ${group.currency}`);
      lines.push("");
    }
    lines.push(buildSummaryTable(group));
    lines.push("");
  }

  // Charts section
  if (chartCaptures.length > 0) {
    lines.push("## Charts");
    lines.push("");
    const chartLabels: Record<string, string> = {
      pie: "Distribution by Category",
      trend: "Trend Over Time",
      cumulative: "Cumulative Chart",
    };
    for (const capture of chartCaptures) {
      lines.push(`### ${chartLabels[capture.chartType] || capture.chartType}`);
      lines.push("");
      if (capture.captureMethod === "placeholder") {
        lines.push("> ⚠️ Chart capture unavailable");
      } else {
        // Embed as base64 image
        lines.push(`![${chartLabels[capture.chartType]}](${capture.imageData})`);
      }
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  lines.push(`*Generated by URI Finance on ${generatedAt.toLocaleString()}*`);

  return lines.join("\n");
}
