// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug: Log Supabase configuration
if (typeof window !== 'undefined') {
  console.log('Supabase URL:', SUPABASE_URL ? 'SET' : 'MISSING');
  console.log('Supabase Key:', SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'MISSING');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: async (url: string | Request, options: RequestInit = {}) => {
      try {
        const response = await fetch(url, options);
        // Suppress 403 errors for logout requests (common when session is already invalid)
        if (response.status === 403 && url.toString().includes('/logout')) {
          // Return a successful response to prevent errors from bubbling up
          return new Response(JSON.stringify({}), { status: 200, statusText: 'OK' });
        }
        return response;
      } catch (error) {
        console.debug('Supabase fetch error:', error);
        throw error;
      }
    },
  },
});